-- Guía de Barrios — tabla de opiniones + vista de agregados.
--
-- Correr una sola vez en el SQL Editor de Supabase.
-- Antes de esto, las respuestas del formulario iban a Web3Forms y terminaban
-- como un email suelto: no se podían contar, filtrar ni publicar. Esta tabla es
-- el activo real de la sección.

create table if not exists public.barrio_opiniones (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),

  -- ── Quién responde (define el peso de la respuesta) ──────────────────────
  -- barrio guarda el SLUG canónico de lib/barrios.js, no el nombre escrito.
  barrio       text not null,
  -- Texto libre solo cuando barrio = 'otro'.
  barrio_otro  text,
  relacion     text not null check (relacion in ('vivo', 'vivi', 'propietario', 'trabajo')),
  antiguedad   text not null check (antiguedad in ('menos1', '1a5', '5a10', 'mas10')),

  -- ── Dimensiones puntuables 1..5 (el corazón del dataset) ─────────────────
  tranquilidad     smallint check (tranquilidad     between 1 and 5),
  seguridad        smallint check (seguridad        between 1 and 5),
  acceso_invierno  smallint check (acceso_invierno  between 1 and 5),
  servicios        smallint check (servicios        between 1 and 5),
  conectividad     smallint check (conectividad     between 1 and 5),
  transporte       smallint check (transporte       between 1 and 5),
  vida_barrio      smallint check (vida_barrio      between 1 and 5),

  -- ── Recomendación (las métricas titulares) ───────────────────────────────
  rec_vivir        text check (rec_vivir    in ('si', 'reparos', 'no')),
  rec_invertir     text check (rec_invertir in ('si', 'reparos', 'no')),
  volveria_elegir  boolean,          -- el NPS del barrio
  sin_auto         boolean,
  perfiles         text[] not null default '{}',

  -- ── La única pregunta abierta ────────────────────────────────────────────
  cita             text check (cita is null or char_length(cita) <= 280),
  -- Independiente de `estado`: una respuesta puede computar en los promedios
  -- aunque su frase no se publique.
  cita_publicable  boolean not null default false,

  -- ── Contacto (opcional) ──────────────────────────────────────────────────
  nombre           text,
  email            text,
  quiere_informe   boolean not null default false,

  -- ── Moderación ───────────────────────────────────────────────────────────
  -- Nada se publica sin aprobación explícita.
  estado           text not null default 'pendiente'
                     check (estado in ('pendiente', 'aprobada', 'rechazada')),
  nota_interna     text,

  -- ── Antifraude ───────────────────────────────────────────────────────────
  -- Hash de la IP, nunca la IP. Sirve para detectar que alguien cargue 40
  -- respuestas del mismo barrio. Sin esto el dataset es trivialmente
  -- manipulable, y la credibilidad es justamente el activo que se construye.
  ip_hash          text,
  user_agent       text
);

create index if not exists barrio_opiniones_barrio_idx
  on public.barrio_opiniones (barrio);

create index if not exists barrio_opiniones_estado_idx
  on public.barrio_opiniones (estado, created_at desc);

-- Detección de carga masiva desde un mismo origen.
create index if not exists barrio_opiniones_iphash_idx
  on public.barrio_opiniones (ip_hash, created_at desc);

-- ── RLS ────────────────────────────────────────────────────────────────────
-- Sin políticas: nadie entra con la clave pública. Toda la lectura y escritura
-- pasa por el servidor con SUPABASE_SECRET_KEY (que omite RLS), igual que el
-- resto de las tablas del panel.
alter table public.barrio_opiniones enable row level security;

-- ── Vista de agregados ─────────────────────────────────────────────────────
-- Las fichas de barrio leen de acá: un registro ya calculado por barrio, en vez
-- de traerse todas las opiniones y promediar en JS.
--
-- Solo computa las APROBADAS. `n` es la cantidad de respuestas y es lo que
-- decide qué se puede mostrar:
--   n < 5    → no se muestra ningún promedio
--   n 5..14  → números absolutos, nunca porcentajes ("7 de 9 vecinos")
--   n >= 15  → recién ahí porcentajes, siempre con el n al lado
-- El umbral se aplica en lib/barrioOpiniones.js, no acá, para que la vista
-- siga siendo datos crudos.

create or replace view public.barrio_agregados as
select
  barrio,
  count(*)::int                                          as n,
  count(*) filter (where relacion = 'vivo')::int          as n_residentes,
  count(*) filter (where antiguedad in ('5a10','mas10'))::int as n_veteranos,

  round(avg(tranquilidad)::numeric,    1) as tranquilidad,
  round(avg(seguridad)::numeric,       1) as seguridad,
  round(avg(acceso_invierno)::numeric, 1) as acceso_invierno,
  round(avg(servicios)::numeric,       1) as servicios,
  round(avg(conectividad)::numeric,    1) as conectividad,
  round(avg(transporte)::numeric,      1) as transporte,
  round(avg(vida_barrio)::numeric,     1) as vida_barrio,

  count(*) filter (where rec_vivir    = 'si')::int as rec_vivir_si,
  count(*) filter (where rec_invertir = 'si')::int as rec_invertir_si,
  count(*) filter (where volveria_elegir)::int     as volveria_si,
  count(*) filter (where volveria_elegir is not null)::int as volveria_total,
  count(*) filter (where sin_auto)::int            as sin_auto_si,
  count(*) filter (where sin_auto is not null)::int as sin_auto_total
from public.barrio_opiniones
where estado = 'aprobada'
group by barrio;
